### PR TITLE
Non-canonical infinity point & bad flags in BLS12-381 serialization should fail

### PR DESCRIPTION
**Pull request by mmagician**
## Description

Follow-up to https://github.com/arkworks-rs/curves/pull/157, the original is stale.

Thanks @ArnaudBrousseau for providing a test for bad flags (lmk if you'd like me to add you as co-author on the commit here)

closes: #157 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by ArnaudBrousseau — APPROVED** [review]
The new flag logic and tests look good to me! Thanks for taking this on so quickly @mmagician!

**Review by Pratyush — APPROVED** [review]

**Comment by Pratyush** [comment]
Thanks for the great PR @mmagician! Could you add a CHANGELOG entry as this is an important fix? Thanks!

**Comment by mmagician** [comment]
@Pratyush It's actually a breaking change no?

**Comment by Pratyush** [comment]
In Rust breaking changes are only when the API changes, not necessarily behaviour

**Comment by mmagician** [comment]
@Pratyush Thanks, I moved it to `Bugfixes`.

**Review by Pratyush — APPROVED** [review]

**Pull request merged**
