### PR TITLE
Bw6-761 optimized Miller loop

### PR DESCRIPTION
**Pull request by mmagician**
## Description

Companion to https://github.com/arkworks-rs/algebra/pull/617

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by weikengchen** [comment]
Just to check: is the pairing equivalent or not? --- later would be breaking.

**Comment by mmagician** [comment]
The pairing's equivalent. But you bring up a good point - the parameters for the Miller loop need to be adjusted, so maybe the `ec` [change](https://github.com/arkworks-rs/algebra/pull/617) should be considered as a breaking change?
This would only be breaking if someone had their own implementation of another bw6 curve and was already using arkworks 0.4+. In the end, we should probably stick to best practices though.

**Comment by weikengchen** [comment]
If the pairing is equivalent, then I think it would be completely okay---we do this, but just leave a changelog entry that the parameters have been changed.

**Comment by weikengchen** [comment]
^ and in this case, `ec` change should surely be a breaking change.

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
I believe we can merge this one first and then see if the test in the algebra passes.

**Comment by Pratyush** [comment]
@mmagician Let's merge this once the parameters are updated.

**Review by Pratyush — APPROVED** [review]

**Comment by mmagician** [comment]
I temporarily switched to a branch `bw6-optimization` from algebra - this should allow us to verify that all tests are indeed passing, and once this PR is merged, we can also merge https://github.com/arkworks-rs/algebra/pull/617, and finally update the patch.

**Pull request merged**
