### PR TITLE
Add MSM benchmark

### PR DESCRIPTION
**Pull request by Pratyush**

### CODE REVIEW

**Comment by ValarDragon** [comment]
Should we add MSM benchmarks closer to the actual MSM logic in `algebra`? (And then perhaps make the benchmark crates there actually import `curves`?)

**Comment by Pratyush** [comment]
You run into some circular dependency issues if you do that. I would not be averse to adding benchmarks there, but I also don't want to split the benchmarks across two repos

**Comment by ValarDragon** [comment]
Seems a bit odd to me to keep it here, separated from the MSM code

**Comment by Pratyush** [comment]
Hmm but the same logic applies to benchmarks for the other operations also, no?

**Comment by ValarDragon** [comment]
Outside of serialization, I do think they should be in algebra!

Maybe what we can do is move the macros to a repository in `algebra`, and then expose convenience benchmarks here that call the macros defined in algebra.

(I didn't realize that other benchmarks were here, no need to block this PR then. I think we should eventually do the above tho)

**Review by ValarDragon — APPROVED** [review]

**Comment by Pratyush** [comment]
Hmm this does relate to https://github.com/arkworks-rs/algebra/issues/34, which would enable similar benchmarks. Maybe adding a script which performs a clone and then benchmarks/tests would suffice?

**Comment by ValarDragon** [comment]
I'd prefer to minimize the number of repos you need to switch between to execute benchmarks after making a small change

**Comment by Pratyush** [comment]
Ah so you're saying we should move `curve-benches/src` to a crate in algebra, and then have a version of the files in `curve-benches/benches` to benchmark `bls21_381`/`mnt4`/`whatever`? And similarly for tests?

**Comment by ValarDragon** [comment]
yeah exactly! So the `src` would be in an algebra crate, and so would benchmarks on `algebra`'s test-curves. Then this repo would have benchmarks on all the curves

I think something similar ought to work for tests?

**Pull request merged**
