### PR TITLE
Upgrade ff for curves.

### PR DESCRIPTION
**Pull request by sunhuachuang**
## Description

Upgrade ff for curves.

- [x] Depend on algebra hotfix [391](https://github.com/arkworks-rs/algebra/pull/391) & [392](https://github.com/arkworks-rs/algebra/pull/392) 
- [x] Depend on algebra changes [393](https://github.com/arkworks-rs/algebra/pull/393)
- [ ] Depend on r1cs-std upgrade to latest

#### Main change
1. use `#[derive(MontConfig)]` for all `Fq`/`Fr`.
2. use `MontFp`, `QuadExt`, `CubicExt`.
3. remove unused `[rustfmt::skip]` for cleanup & cargo fmt --check.
4. upgrade test code for new ff.
5. rename `FxParams` to `FxConfig`

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (upgrade-ff)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
Thanks a lot!

**Comment by Pratyush** [comment]
Quick question: would it be possible to port over some of the sage scripts in this PR: https://github.com/arkworks-rs/curves/pull/95/

The main aim is to check that the generator we specify in the Rust files actually is a generator.

If not, I can file a quick issue to add it and we can address it in a followup PR

**Comment by sunhuachuang** [comment]
Sure, I get the generator in the parameters from sagemath, like: 
```
k = GF(258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177, modulus="primitive")
k.gen()
```
But there are some big numbers(mnt4_753) that I can't get quickly, so I use previous `GENERATOR * R.inverse()` to get it, so I'm not sure how to write this sage script, need you followup.

And, I will add this [test_constants (algebra/test-curves)](https://github.com/arkworks-rs/algebra/blob/master/test-curves/src/bls12_381/fq.rs#L17) to all Fq/Fr with previous constants and it will feel better.

**Comment by Pratyush** [comment]
> But there are some big numbers(mnt4_753) that I can't get quickly, so I use previous GENERATOR * R.inverse() to get it, so I'm not sure how to write this sage script.

For the numbers that are hard to factorize, one can try consulting other sources (like libsnark), and copying the generators from there. Also, you only really need a partial factorization of MODULUS - 1; you can use a tool like https://www.alpertron.com.ar/ECM.HTM to break it down to large factors, and then the sage script can verify that `GENERATOR^LARGE_FACTOR != 1`.

> Is it like in bls12_377/fr.rs, and add to all Fq/Fr ?

Sorry, I should have linked the earlier sage scripts, I meant more like [this one](https://github.com/arkworks-rs/curves/blob/e8d3b366d4c92c4cd2d70827e4eab1d54f57a390/bls12_377/scripts/base_field.sage). We can make a `scripts` folder in each crate, and add sage scripts for both the `base_field` and the `scalar_field`.

> And, I will add this [test_constants (algebra/test-curves)](https://github.com/arkworks-rs/algebra/blob/master/test-curves/src/bls12_381/fq.rs#L17) to all Fq/Fr with previous constants and it will feel better.

Finally, regarding the `test_constants` test, we can instead use the strategy here: https://github.com/arkworks-rs/algebra/blob/a40bcae1f5a9759c5202b70bd8d353e75086bdb5/test-curves/src/bls12_381/tests.rs#L15

here `mont(6, 4)` specifies the number of limbs for Fq and Fr, respectively. So, for example for `bn254`, we'd add `mont(4, 4)`.

**Comment by sunhuachuang** [comment]
Cool, I will instead use `mont` to test Fq and Fr. And I will add this `scripts/xx.sage`.

**Comment by Pratyush** [comment]
Great, thanks!

**Comment by sunhuachuang** [comment]
Hi pratyush, 
can you hotfix this line: https://github.com/arkworks-rs/algebra/blob/master/test-templates/src/lib.rs#L294 
it missing `generate_field_test!($($tail)*);`

BTW, I found that [`Fp12Parameters`](https://github.com/arkworks-rs/algebra/blob/master/ff/src/fields/models/fp12_2over3over2.rs#L13) is not changed to `Fp12Config` like others, is it special?

**Comment by Pratyush** [comment]
Done in this PR: https://github.com/arkworks-rs/algebra/pull/393

I fixed both issues, thanks for catching this!

**Comment by Pratyush** [comment]
Done in this PR: https://github.com/arkworks-rs/algebra/pull/393

I fixed both issues, thanks for catching this!

**Comment by sunhuachuang** [comment]
Here https://github.com/arkworks-rs/algebra/blob/master/test-templates/src/fields.rs#L457 need to fix.
Replace with `let mut serialized = vec![0u8; buf_size + 1];` because this `buf_size` is calculated by `EmptyFlags`, but here will use `SWFlags`, so add one size for test.

**Comment by sunhuachuang** [comment]
I had renamed `Params` to `Config`. And here https://github.com/sunhuachuang/r1cs-std , also fixed the rename and test code in `r1cs-std` (curve will deps), when algebra#393 is merged, I will make a PR to r1cs-std `fix-ff` branch.

**Comment by weikengchen** [comment]
Thanks a lot!

**Comment by Pratyush** [comment]
Merged #393

**Pull request merged**
