### PR TITLE
Add curve BW6-767

### PR DESCRIPTION
**Pull request by mmagician**
## Description

The outer curve whose scalar field is the base field of [BLS12-381](https://github.com/arkworks-rs/curves/blob/5a41d7f27a703a7ea9c48512a4148443ec6c747e/bls12_381/src/fields/fq.rs).

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by mmagician** [comment]
@yelhousni

**Review by Pratyush — APPROVED** [review]

**Comment by mmagician** [comment]
Still need to fix the tests, I think the Pairing config is off

**Comment by mmagician** [comment]
It seems that the [optimized final exponentiation in BW6 model](https://github.com/arkworks-rs/algebra/blob/b71caecb0f31f545b8bd7a8062000c7b6d7b190f/ec/src/models/bw6/mod.rs#L189) is specific to the BW6-761 curve. For now I've updated the pairing parameters to match the new [Miller loop algorithm](https://github.com/arkworks-rs/algebra/pull/617).

**Comment by mmagician** [comment]
Superseded by https://github.com/arkworks-rs/curves/pull/156

**Pull request closed without merging**
